<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QB-KRT-10370" failures="1" tests="2" name="com.runners.TestRunner" time="6.833" errors="0" timestamp="2022-04-06T19:51:36 IST" skipped="0">
  <testcase classname="com.runners.TestRunner" name="runScenario" time="3.354"/>
  <system-out/>
  <testcase classname="com.runners.TestRunner" name="runScenario" time="3.479">
    <failure message="expected [Log out] but found [LOG OUT]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Log out] but found [LOG OUT]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.stepDef.LoginPageSteps.userShouldBeAbleToLoginSuccessfully(LoginPageSteps.java:31)
at âœ½.user should be able to login successfully(file:///home/qbuser/Kadavil/IdeaWorkSpace/Selenium4CucumberHybridFramework/Features/Login.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.runners.TestRunner -->
